language: csharp
solution: Sibusten.Philomena.Client.sln
mono: none
dotnet: 5.0.101
os: linux
dist: xenial

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

install:
  - dotnet restore

script:
  - dotnet build --no-restore -c $CONFIGURATION

after_success:
  - dotnet test --no-build --verbosity normal

before_deploy:
  - dotnet pack ./Sibusten.Philomena.Client/Sibusten.Philomena.Client.csproj -c Release

deploy:
  on:
    tags: true
  provider: script
  edge: true
  script: dotnet nuget push ./Sibusten.Philomena.Client/bin/Release/Sibusten.Philomena.Client.*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
